export default class CommonEvent {
	/**获取微信场景值 */
	static COMMONEVENT_GETSCENEID = "COMMONEVENT_GETSCENEID"
	/**领取收藏有礼结束 */
	static COMMONEVENT_GETCOLLECTAWARD = "COMMONEVENT_GETCOLLECTAWARD"
	/**被邀请信息 */
	static COMMONEVENT_INVITEE = "COMMONEVENT_INVITEE";

	static COMMONEVENT_ADDONGAMESHOW = "COMMONEVENT_ADDONGAMESHOW"
	static LOADING_FINISH = "LOADING_FINISH"
	static CLIENT_SEND_LOG = "CLIENT_SEND_LOG"

	static ON_SHOW = "ON_SHOW"
	static ON_HIDE = "ON_HIDE"

	/** 获取IP省份成功 */
	static GET_IPINFO_SUCCESS = "GET_IPINFO_SUCCESS"
	/** 获取IP省份失败 */
	static GET_IPINFO_FAIL = "GET_IPINFO_FAIL"
	/** 白名单状态变化 */
	static WHITE_LIST_CHANGE = "WHITE_LIST_CHANGE"
}
